services:
  linux-dev-desktop:
    network_mode: "host"
    volumes:
      - ./_data/${MYUSERNAME}/.ssh:/home/${MYUSERNAME}/.ssh
      - ./_data/${MYUSERNAME}/git-repos:/home/${MYUSERNAME}/git-repos
    container_name: linux-dev-desktop
    build:
      context: .
      args:
        USERNAME: ${MYUSERNAME}
        PASSWORD: ${PASSWORD}
    restart: always
    environment:
      - USERNAME=${MYUSERNAME}
      - MYUSERNAME=${MYUSERNAME}

