services:
  apt-cache:
    build: ./aptCacher/
    ports:
      - "3142:8700"
    volumes:
      - cacheVol:/cache
  linux-dev-desktop:
    network_mode: host
    volumes:
      - linuxdevDataGitRepos:/home/${MYUSERNAME}/git-repos
      - linuxdevDataMozilla:/home/${MYUSERNAME}/.mozilla
      - linuxdevHome_ssh:/home/${MYUSERNAME}/.ssh
      - linuxdevDataetc_ssh:/etc/ssh
      - ./etc/sshd_config:/etc/ssh/sshd_config
    container_name: linux-dev-desktop
    build:
      context: .
      args:
        USERNAME: ${MYUSERNAME}
        PASSWORD: ${PASSWORD}
        CACHE_URL: ${CACHE_URL}
    restart: always
    depends_on:
      - apt-cache
    environment:
      - USERNAME=${MYUSERNAME}
      - MYUSERNAME=${MYUSERNAME}
      - PASSWORD=${PASSWORD}
volumes:
  linuxdevDataGitRepos:
  linuxdevDataMozilla:
  linuxdevDataetc_ssh:
  linuxdevHome_ssh:
  apt_cache:
  cacheVol:
